/**
 * AUTO-GENERATED by openapi-typescript from packages/specs/dist/openapi.json.
 * Do not edit by hand — run `pnpm spec:codegen` to regenerate.
 *
 * This is a minimal stub. Run codegen after `pnpm spec:bundle` to populate.
 */

export type paths = Record<string, never>;
export type components = { schemas: Record<string, never> };
